Add WINDOWS_IGNORE_PACKING_MISMATCH macro to avoid C2338 error on new WinSDK
Avoid "Error C2338: Windows headers require the default packing option. Changing this can lead to memory corruption."